server:   
  servlet:
    context-path: "/ms-movie"    

spring:
  profiles:
    active: default
  application:
    name: /ms-movie  
  h2:
    console:
      enabled: true
      path: /h2-console 
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect